### PR TITLE
S3 uploader

### PR DESCRIPTION
**Pull request by Arau**
Preparing documentation before merge.

### CODE REVIEW

**Comment by Arau** [comment]
Overview Docs pushed

**Review by actionbuddha — COMMENTED** [review]
This is fantastic work - rather more complete than I was expecting! One question, why do we stage to an rsync bucket first rather than simply have an escort container push the data to S3?

**Review by avestuk — APPROVED** [review]
LGTM

**Comment by Arau** [comment]
> This is fantastic work - rather more complete than I was expecting! One question, why do we stage to an rsync bucket first rather than simply have an escort container push the data to S3?

That is a really good question. There are a few reasons I considered for that. Whether they are more valid than using  the uploader as a side car or no is up to debate :). 

- Decoupling of concerns. 
  - The Uploader can run in a different namespace, with very specific resource allocation making the solution easier to compartmentalise.
  - By running the uploader in a different Pod, we avoid tightening the S3 logic. If we want to add support for other backends. The production deployment would not have any changes. Just the uploader.
- Pod lifecycle vs Container lifecycle. 
  - We can define the periodicity of the backups as a cronjob in the Kubernetes Objects. I think it is more visible than injecting a configMap to define when the backups happen. How would look like if you need to change the periodicity when running the uploader as a side car? We would need to have the logic to reconcile the timings periodically. It wouldn't be a big deal, but is added complexity.
  - The visibility of the output of a backup is easily traceable when running as a Pod, you can see if the latest Pod that run the uploader finished correctly. Even the history by checking all the Pods that run the uploader. If running as a container. You would have to inspect the logs of a container. Since it can restart an undefined number of times, the logs of the backups would be lost giving no capacity to the operator to know the status of previous backups.
- The Pod that uploads to S3 have the AWS cli which means that I'm using a fairly big OCI images. I initially build it to go together, but then I compromise the startup response time of the Production application to spin up a big image. There are options to use a smaller image with the cli installed. However I haven't investigated yet.
- The uploader is designed to be able to execute the work that needs to be done and finish. By using a container as a side car, that would need to be a long running service. Even though, is fairly trivial, there are implications, such as memory leaks, or the resources used be the need for reconciling state. The personal choice I made was to have an rsync server as a long running process, rather than a self implemented service. 

Of course there are very strong reasons to run the the uploader as a side car.
- Moving all data from one Pod to another to end up uploading to a 3rd party. It is a unnecessary use of network traffic when it can go straight to the 3rd party.
- It also adds complexity by the fact of having to set up the rsync server and its configuration.

As a conclusion, I tried to trade a fast development solution (uploader as a sidecar) and a less resource consumption vs operability and leverage of kubernetes tooling available  (uploader isolated).

**Pull request merged**
