### PR TITLE
Change PostgreSQL example to use stateful set

### PR DESCRIPTION
**Pull request by avestuk**
These changes create a serviceAccount, Service, configMap and Stateful set that create a PostgreSQL deployment of a single pod. The pod is accessible through the service and is backed by a StorageOS volume. 

Usage of this example will be laid out in our documentation.

### CODE REVIEW

**Comment by Arau** [comment]
Lets try to keep branch names meaningful.

**Review by Arau — APPROVED** [review]

**Comment by Arau** [comment]
I really like the use of config maps for config info such as ENV variables. It would be great that different examples have a README, even a simple one with copy&paste from the docs PR.

**Comment by avestuk** [comment]
> Lets try to keep branch names meaningful.

Yes I'll try to think more about what the whole task at hand is before creating a branch name next time. 

>... different examples have a README

Sure I can add that in.

**Comment by avestuk** [comment]
Added README files for all kubernetes examples.

**Review by actionbuddha — APPROVED** [review]

**Pull request merged**
